# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Seminario NTV
tagline:             'Estudios bíblicos'
description:         'Este seminario ofrece estudios bíblicos para entender el verdadero llamado de Dios a los cristianos, como compartir su palabra y entender su palabra.'
url:                 
baseurl:             /lanyon
paginate:            5

# About/contact
author:
  name:              Gerardo Alvez
  url:               https://twitter.com/alvezgr
  email:             alvezpope@gmail.com

# Custom vars
version:             1.0.0
